### ISSUE TITLE
 Add MinIO support for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-minio#2]
## Description

[MinIO] is an open source cloud-native high-performance object storage service. 
This project will use minio's native SDK to implement [go-storage]'s Storager interface, 
enabling users to manipulate data on minio servers through a unified interface.

## Roadmap

- [x] Choose a well maintained MinIO library
- [x] Implement all interface that Storager required
- [x] Setup integration tests
- [x] Add docs in [site](https://github.com/aos-dev/site)
- [x] Add examples in [example](https://github.com/aos-dev/go-storage-example)

[MinIO]: https://min.io/
[go-storage]: https://github.com/aos-dev/go-storage/

**Comment by Xuanwo** [comment]
@aeinrw is responsible for this issue.

**Comment by Prnyself** [comment]
Congratulations to @aeinrw for this wonderful contribution!
